---
- name: configure security policies
  ansible.builtin.command: update-crypto-policies --set

- name: restart sshd
  ansible.builtin.service:
      name: sshd 
      state: restarted
  listen: "restart secure services"

